server:
  port: 80

spring:
  datasource:
    username: pinfuyu
    password: qwer1234
    url: jdbc:mysql://123.207.13.58:3306/paydata?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    static-path-pattern: /static/**


#showSql
logging:
  level:
    com:
      example:
        mapper : debug

mybatis-plus:
  mapper-locations: classpath:*sqlmap/*Mapper.xml
  typeAliasesPackage: com.pay.**.bean